trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    py36:
      python.version: '3.6'
      tox.env: py36
    py37:
      python.version: '3.7'
      tox.env: py37

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: '$(python.version)'
  name: 'py'

- script: |
    $(py.pythonLocation) -m pip install --disable-pip-version-check --upgrade pip
    $(py.pythonLocation) -m pip install tox
    $(py.pythonLocation) -m pip install --editable .
  displayName: 'dependencies'

- script: |
    tox -e $(tox.env)
  displayName: 'test'