trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    py36:
      python.version: '3.6'
      tox.env: py36
    py37:
      python.version: '3.7'
      tox.env: py37

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: '$(python.version)'

- script: |
    $(python.version) setup.py develop
    $(python.version) -m pip install tox
  displayName: 'dependencies'

- script: |
    tox -e $(tox.env)
  displayName: 'test'